import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Nav } from '@/components/Nav'

const inter = Inter({ subsets: ['latin'] })
const navData = [
  {
    name: 'HOME',
    link: '/',
    icon: 'faHome'
  },
  {
    name: 'LOG IN',
    link: '/',
    icon: 'faRightToBracket'
  },
  {
    name: 'SIGN UP',
    link: '/',
    icon: 'faUserPlus'
  },
  {
    name: 'COLLECTION',
    link: '/',
    icon: 'faHeart'
  },
]
export const metadata: Metadata = {
  title: 'My Pexels Collection',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav data={navData}/>
        {children}
      </body>
    </html>
  )
}
